sudo: false
os:
  - linux
  - osx
language: rust
rust:
#  - stable
#  - beta
  - nightly
#matrix:
#  allow_failures:
#    - rust: nightly
script:
  - cargo --version
  - rustc --version
  - cargo build --verbose
  - cargo test --verbose
