[package]
name = "human-size"
description = "Sizes for humans."
keywords = ["size", "human", "readable"]
version = "0.1.1"
authors = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
repository = "https://github.com/Thomasdezeeuw/human-size-rs"
readme = "README.md"
license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "Thomasdezeeuw/human-size-rs" }
appveyor = { repository = "Thomasdezeeuw/human-size-rs" }

[dependencies]
